### PR TITLE
Add pandapower to the LFE landscape

### PR DESCRIPTION
**Pull request by nicorikken**
Pandapower is popular for power systems caculations in Python and is used by
some LFEnergy members. This addition was checked with the Pandapower project in
advance: https://github.com/e2nIEE/pandapower/issues/1332

Signed-off-by: Nico Rikken <nico.rikken@alliander.com>

### CODE REVIEW

**Comment by nicorikken** [comment]
I've submitted an issue with the bot, as a single Crunchbase wouldn't cut it for this entry I think.

**Comment by jmertic** [comment]
@nicorikken Thanks for submitting this. Generally, we recommend whoever is the primary contributor organization or owner is the Crunchbase to use. Let me know if that could work.

**Comment by nicorikken** [comment]
@jmertic I'll ask the project because I can't decide.

**Comment by nicorikken** [comment]
@jmertic I listed an organization instead of a Crunchbase link, as recommended in https://github.com/cncf/landscapeapp/issues/767 Now it passes the CI job.

**Comment by jmertic** [comment]
Excellent - thank you @nicorikken !

**Pull request merged**
