### PR TITLE
Import in Open Sustainable Technology projects

### PR DESCRIPTION
**Pull request by jmertic**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203844311454500

### CODE REVIEW

**Comment by jmertic** [comment]
We have a working build!

https://deploy-preview-757--lfenergy.netlify.app/pages/opensustaintech

@Ly0n @joshhopkins we still need to do the nicer visual layout and clean up the data ( unless we like all the alligator images ;-) ), but at least we have the data over. Let me know your thoughts.

**Comment by Ly0n** [comment]
Great to see that this is already up and running! 

I have been thinking for the last few days about how we can solve the problem with the logos. Maybe we can automate capturing the logo url via the current scripts [AwesomeCure](https://github.com/protontypes/AwesomeCure). Here's what I'd like to try this weekend:

1. get all the URLs/paths from the README. 
2. get all URLs/paths that end in .png. 
3. create absolute paths from the URLs.
4. download all PNG.
4. the first URL with a larger PNG file is most likely the image logo. 
5. if no larger PNG could be found, the image of the organization's namespace/username will be used.
6. store the logo URL

This way we should be able to create a dataset that can be cleaned up with little effort. 
The method could also be interesting for @andrew and his work on https://ecosyste.ms/.

**Comment by jmertic** [comment]
Hey @Ly0n - it's a good idea, but we need pure SVGs for logos. Generally, getting them all is a trudge; we can create ones based on the sponsoring organization if required.

**Comment by jmertic** [comment]
@Ly0n @joshhopkins - we now have it laid out visually - check it out at https://deploy-preview-757--lfenergy.netlify.app/open-sustainable-energy

**Comment by Ly0n** [comment]
You really did it. Impressive!

**Comment by jmertic** [comment]
Thanks! Still some work to do on fit and finish - but we are in a good place!

**Pull request merged**
